gautamkrishnar/socli

socli/socli.py
=> bcolors simple implementation, for text formatting and coloring

README.md
backers and sponsors will automatically show up on your readme. 
add badges on top
more info: https://github.com/opencollective/opencollective/wiki/Github-banner
=> ad backers & sponsors to readme

socli/socli.py
=> Fixed issue#30

socli/socli.py
This should fix that issue. I just copied the interactive mode as of 7364b05.
=> fix #39 by using non-urwid interactive mode on windows

socli/socli.py
=> Verify certificates during request.get()

socli/socli.py
Changed the error message for StackOverflow captcha because it actually doesn't require you to verify your identity. Simply waiting a few seconds and querying again should unblock you.
=> Handled Google captcha error and changed Captcha Error message.

Portfile, socli/socli.py
changed opening url to a system call for better support
fixes: #80 
fixes: #12
=> fixed (default) browser support

Portfile, socli/socli.py
Fixes an issue that came up in a comment #93.
=> Mac browser fix

socli/socli.py
Socli -b hot
will present 10 questions under hot tab in an interactive manner.
same can be done for other tabs as well. 
This will work for Linux.
The function Socli_browse_interactive_windows() is yet to be implemented.
=> -b browse tag

socli/socli.py
This is in "socli -u" processing.
=> #112 Check that questions have been asked before dividing by the count

Portfile, socli/socli.py
This pull request does handle URLError for both python 2 and 3 in the userpage function.
=> URLError handling for py2 and 3

README.md
add about error with SSL ST INIT's handling
=> add attribute error handling in Readmd file

socli/socli.py
#120 fixed. 
I removed the use of arrows in the UnicodeText function as it was not being supported in certain versions. Instead I have used simple letters to execute respective commands.
=> Fixed letters to their respective commands

socli/socli.py
#121 resolved.
added 3 features in the user page function ( c : checking another user, d: deleting current user files, any key: save and exit)
=> Improvised --user command

socli/socli.py
Stack overflow has changed some tags and classes. I fixed the parsing for vote count. Probably more work is needed, but at least I get output and can look at answers.
=> Fixed soup parsing for vote score.

.travis.yml, socli/search.py
All tests in test_socli.py now pass. I have left in some other code related to the --browse feature since issue #25 is still open. Just cleaned up enough to get the unit tests passing. See https://github.com/gautamkrishnar/socli/issues/149#issuecomment-515516260
=> Remove buggy br condition

socli/search.py
Changed the google_search_url to make sure the only the SO results appear in google search results and not any of its subdomains.
=> Different Subdomains #157

.all-contributorsrc, .travis.yml, CHANGELOG.rst, README.md, README.rst, deploy-check.py, setup.py, socli/search.py
Update `use-stackexchange-api` branch with master so it's up to date when working on using PyStackExchange to do the searching.
Ref: #178
=> Update use-stackexchange-api branch with master

socli/socli.py
I've left the range-the number of results that's checked at 8
(I wasn't sure if it was 9 or 10 that I could max it out and didn't want the loop to go out of bounds)
=> Fixing 404

socli/search.py, socli/socli.py
Did the necessary changes to fix #212 
Please review the same and lemme know if I need to change something.
=> Fixing the 404 error

socli/printer.py, socli/search.py, socli/socli.py, socli/tests/test_socli.py, socli/tui.py
added c toggle to show comments and v to go back to answers
=> Comments toggle

socli/printer.py, socli/search.py, socli/socli.py, socli/tui.py
As the traceback said,  more values were being returned from `get_question_stats_and_answer_and_comments()` than expected and less number of values were passed to `tui.QuestionPage()`. Fixes #201
=> Fixed socli -iq command

socli/search.py
Hie @gautamkrishnar,
Did the necessary changes to fix issue #228. Please review the same and do let me know if any more changes are needed to be done.
Cheers,
Anshik B.
=> Fixed issue #228 : Search Not Working

socli/printer.py, socli/tui.py
=> Feature [issue #216]: Added option to return to original question after visiting its duplicate

socli/search.py
PR adds feature that the accepted answer will we the first answer visible and the whole answer will be surrounded by ====accepted-answer=====<Answer>=====accepted-answer===== tags which instantly notifies to the user which is the accepted answer.Future PR may add color to make it more obvious.
=> Added support for highlighting the accepted answer.

CONTRIBUTING.md, README.md
#250  
Kindly do check and merge it @gautamkrishnar 
Kindly do add the labels also to issue and PR too
=> Contributing file 

CONTRIBUTING.md
=> Fix GitHub format in CONTRIBUTING.md

socli/search.py
Potential fix for #273
**Additional Note**
I have removed the explicit check for Instant answers as they will directly raise an exception in this version
=> Potential fix for google results change(June 2021)

socli/search.py
=> Removed an additional div find

README.md
Hi. Sorry for creating a PR for a very small thing. This is my first ever PR so I'm just trying stuff out. Thanks.
=> corrected potential misspelling of a word in README (vis -> via)

socli/tui.py
=> Store question page as instance variable
