gautamkrishnar/socli

socli/socli.py

Check for color support whether printing colored sentences.
Also changed print functions name to match PIP8 pattern
(https://www.python.org/dev/peps/pep-0008/#function-names)

Check for color support whether printing colored sentences.

---

socli/socli.py

* code wraps to `79` lines
* remove `^M` character at the end of every line

Try to make it pep8 compatible

---

socli/socli.py

I've added support for URLs as requested in issue #10. Please review these changes.

Enhancement: Added URL to any hyperlinked text in a question or answer.

---

socli/socli.py

Answers provided by `socli` come from Stack Overflow, which has an [attribution policy](http://blog.stackoverflow.com/2009/06/attribution-required/). It's pretty typical to include a comment with a link to the SO answer when using code, so it would be good to include the answer link in the output.
This patch adds the question link in a parenthetical under the question title:
```
Question: How do you copy a Lua table by value?
(http://stackoverflow.com/questions/640642/how-do-you-copy-a-lua-table-by-value)
. . .
```
It also changes `question_tittle` to `question_title` which I assume was a typo.
(Disclosure: I work as a Community Manager for Stack Overflow.)

Display links to questions.

---

setup.py
socli/socli.py

SoCLI was unable to show the previous answer by typing 'b' as input for interactive mode. This PR fixes the issue by decrementing the 'cnt' variable(which keep track of current post) which was originally incremented and caused this issue.

Patch#2 by ankit

---

socli/socli.py

Fixed special char display problem

---

socli/socli.py

Git bash supports color font in windows so added a little code in supports_color function to detect the shell and return true if its git bash shell.
Fixed some minor typos and changed long option '--interactive=" to '--interactive' since it does not accept any parameters.

Color support for git-bash in windows 10

---

.gitignore
socli/__main__.py
socli/socli.py

Hi @gautamkrishnar.
I made few changes to the code as below:
* .gitignore/ Added appropriate Python .gitignore.
* socli/__main__.py : this is how main it should be called.
* socli:  there is no reason to call sys.exit, it will exit any way in the end of the function.
I will also suggest you to use regex instead of beautifulsoup library.
there is no complex HTML parsing

Few changes and fixes.

---

socli/socli.py

Currently the footer in interactive mode prompts the user to use the up and down keys to navigate the answers, however the prompt text says "next question" and "previous question".
This changes those prompts to say "next answer" and "previous question" respectively.

Accurate footer text

---

socli/socli.py

When using `socli -iq` and selecting an unanswered question socli just quit without any messages.
This make several issues:
+ You can not read unanswered question
+ Socli will just exit if you select an empty question (disturbing, especially in interactive mode)
+ It looks like a big bug, but it's not.
I just added a pseudo-answer in `answers` list if this one is empty. Like that when selecting an empty question in interactive mode I'm able to read the question and just have a message 'No answers for this question...' which is explicit.

Add text 'No answers for this question ...' to avoid simple exit

---

README.md
README.rst
socli/socli.py

This can be changed back to using Stack Overflow by simply changing the global variable "google_search" to False. This also fixes some errors that the old implementation had because  extracting the links from a google search seems to produce different formats at different times. I added a method fixGoogleURL to fix these different types of links. I'm not sure how the randomizing of the agents work as @gautamkrishnar described in issue #49 but you shouldn't get blocked by google if you don't repeatedly spam commands. Searching like a normal person (at most one search every few seconds) shouldn't cause google to block your IP. 
My merge also contains the updated README on accident. I'm not sure if this is okay, but I'm new to git so sorry about that! Let me know if you want that changed.

Implemented the usage of google search for regular search, interactive search, and manual search

---

README.md
socli/socli.py

I did this because I felt it was more intuitive for new users. By letting the up arrow key be "Previous Answer" and down arrow key be "Next Answer", it mimics the format of a webpage and how it would be if you browse StackOverflow through the browser.

Switched functionality of down and up arrow keys in QuestionPage

---

socli/socli.py

Before, if you search stackoverflow in interactive mode, it would enter the session, but show no results because all of them were never added due to FixGoogleURL. Added an extra case to print "No results" if this happens. 
I resolved a rare bug where links extracted from a google search contained a weird prefix and also allowed meta.stackoverflow/a/*QuestionNumberHere* links to pass through as valid posts.

Some URL fixes and condition checks

---

socli/socli.py

This saves the QuestionPage object after visiting it once during interactive mode. This makes it so you do not issue multiple requests to Stack Overflow when you repeatedly select questions (max requests is equal to the number of questions displayed). This also tremendously speeds up displaying a question when visiting it again after the first time in the same session.

Caching pages has been implemented for interactive mode

---

socli/socli.py

When in interactive mode, I made it so that prompt now says that valid keys are 0-(number of questions) and that the program will ask you to try again if you select a number outside of this range rather than exit.

Feature: Ask again if invalid question number is chosen in interactive mode

---

socli/socli.py

Check if the tuple `userprofile.top_answer_tags.fetch()` is empty or not.
When a Stackoverflow user didn't answer or ask questions, the original code raises an Exception 
`except Exception as e`.
The new code is more explicit; it clarifies that the user has no answers or questions without jumping to the exception.

Update socli.py: Checking TopTag tuple emptiness

---

socli/socli.py

If socli is installed on python 2, disconnect from internet and run the following command: 
`socli -u 1`. You'll get the following error message:
```
Traceback (most recent call last):
File "socli.py", line 1221, in <module>
main()
File "socli.py", line 1194, in main
userpage(user)
File "socli.py", line 837, in userpage
except urllib.error.URLError:
AttributeError: 'module' object has no attribute 'error'
```

urlerror handling for both python2 and python3

---

socli/socli.py

This adds 'q' to the footer actions of the interactive mode, allowing to exit socli from the answers screen without going back to the list first.

Add 'q' to close socli in interactive mode

---

setup.py

`if version < '1.0.0':` is just comparing the strings, not the actual version numbers.
According to the [documentation](https://docs.python.org/3/library/sys.html#sys.version), we should rather use `version_info` to extract version information, so I made the following change:
`if version_info[:3] < (2, 0, 0):` # Since Requirements in the README says Python 2.0 or higher

Fixed a bug in setup.py

---

socli/socli.py

This branch adds a feature of viewing the python(2 and 3) documentation from command-line. The documentation can be navigated through the command-line.
Usage: `socli --doc`
Further the user will be guided for the navigation.
In this feature documentation of other languages can be added. 
We are team codeVamps from RGSoC 2018.
Please review and do let us know if we can work on any other issues :)
Thank you!

View documentation

---

setup.py

We're already declaring `include_package_data=True` and `recursive-include socli *` in MANIFEST.in. This ensures that the user_agent.txt file will be available in the package installation
path and thus will be accessible from the package's code.
Location resolved for data_files is unreliable, so let's just get rid of
it since we don't need it.
This fixes https://github.com/gautamkrishnar/socli/issues/148.

No need to declare data_files.

---

socli/socli.py

- sets requests to debug mode on even if no error is thrown.
- useful when trying to debug request/response headers when making queries to websites.

Improve debug mode --debug

---

socli/search.py

This is in reference to issue #179.
I looked through a random sample Q/A page of stackoverflow. Turns out they don't have the previous structure, as @hedythedev pointed out in the comments.
To solve this, I had to refactor the entire line of code that was fetching the stats.
The code now relies on different tags each for the view, vote counts and the post, last activity dates.
**note**: about the view count, I'm having to rely on a css tag. This is because there is only one part of the page that shows the view counter, and I don't think we have any option besides resorting to that.
I'm half confident that stackoverflow might change that class again, soon, and might continue to do so. If we cannot find a better solution, I would suggest that we remove the view counter entirely.
I'm very …

attempted bugfix for issue 179

---

socli/user.py

When `socli --user <id>` is used, and if the user has 0 total_questions, a  ZeroDivisionError will be raised, because of this line:
https://github.com/gautamkrishnar/socli/blob/663290647297a142cc6a81b3a01822828a90d9ee/socli/user.py#L58
since the try-except does not catch ZeroDivision error, it will then be caught as just an `Exception e`:
https://github.com/gautamkrishnar/socli/blob/663290647297a142cc6a81b3a01822828a90d9ee/socli/user.py#L73-L95
Then, in this case it will reach line 90 and tell you to register a new key. Which shouldn't be the case, so what I did was that I wrapped line 58 and print accept rate line in another try-except to catch ZeroDivisionError to prevent asking to register a new API key from happening:
https://github.com/gautamkrishnar/socli/blob/55d7406cf266fd1a595061b …

--user: fix a ZeroDivisionError when total_questions for a user is zero, and fix KeyboardInterrupt

---

socli/search.py

There was a typo in the search.py captcha_check (), corrected the same.

correcting typo in captcha_check

---

socli/search.py

When I was using socli to get answers to my problems, I was surprised to see it give somehow irrelevant results, so I debugged it and found that using the query `site:stackoverflow.com` was better than `site:www.stackoverflow.com`.
Here's an example:
```
python -m socli -iq how to turn a string into a int in python
```

improve google search url to get better results

---

requirements.txt
setup.py
socli/parser.py

added argcomplete library to provide argument complete function #234  , but here it still requires to manually put [ eval "$(register-python-argcomplete socli)"]  at the end of .bashrc file.

argcomplete

---

README.md
socli/search.py

There are small typos in:
- README.md
- socli/search.py
Fixes:
- Should read `extracts` rather than `extacts`.
- Should read `explicitly` rather than `explictly`.
- Should read `automatically` rather than `automaticially`.
Closes: #268

docs: fix a few simple typos

---

socli/search.py

When using socli to search with Google, No results found always returned instead of the actual results. After troubleshooting, I tracked down the bug at line 88 in search.py where it tries to throw an IndexError on purpose when Instant Answers appear.
This should solve issu #287

search.py - fixed instant answer bug 

---

socli/tui.py

No one really asked for this but this is something I added to my local copy of the tool for convenience so figured I'd share.
- Add new menu option in the ui which copies the text from the currently displayed answer to the users clipboard. 
- Feature uses the [pyperclip](https://github.com/asweigart/pyperclip) library.
- Feature is currently bound to the x key. (not sure if there is a better key as c is used for opening the comments)
I use the tool on WSL 2 running Ubuntu 22.04 (Windows 10 PC) which is where these changes were tested

Add feature to copy answer text to clipboard
